name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex
      # - name: Update README PDF images
      #   run: |
      #     sudo apt install poppler-utils
      #     pdftoppm main.pdf ./img/main -png
      # - name: Commit report
      #   run: |
      #     # TODO: Set own GitHub username
      #     git config --global user.name '[USERNAME]'
      #     git config --global user.email '[USERNAME]@users.noreply.github.com'
      #     git add .
      #     git status
      #     git commit -m "[Github Actions]: Update Images for README"
      #     git push
