name: Text quality
on: push
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: LaTeX linter (chktex)
        uses: j2kun/chktex-action@1.0.3
  grammar-spelling:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: "11"
      - name: Install texttidote
        run: |
          wget https://github.com/sylvainhalle/textidote/releases/download/v0.8.2/textidote_0.8.2_all.deb
          sudo dpkg -i textidote_0.8.2_all.deb
          rm textidote_0.8.2_all.deb
      - name: Grammar/Spell check files and linting
        run: textidote
